import os
import random
import time

arr = ["/", "—", "\\", "|"]
dotdot = "."
bar = "["  # 20 len
percentage = 0
MB = 0

print("-= Copyright 1995 Rangecorp Electronic System =-")
print("Reproduction of any material generated by Rangecorp products are trademarked by Rangecorp and any third-party affilates")
time.sleep(0.2)
print("-= TRADELOGO FIRMWARE =-")
print("-= TradeLogo Remote Configuration Spatial System - Installer =-")
time.sleep(2)
print("")
print(" _____ __       _____ _____     _____ _____     _____ _____ _____ _____ ©")
print("|_   _|  |     | __  |   __|___|     |     |___|   __|  _  |  _  |_   _|")
print("  | | |  |__   |    -|   __|___|   --|  |  |___|__   |   __|     | | |  ")
print("  |_| |_____|  |__|__|_____|   |_____|_____|   |_____|__|  |__|__| |_|  ")
time.sleep(1)
print(" TL ReCo Spat | Version 12.1.1 | Profesional License")
print("")
time.sleep(8)
os.system("dir")
time.sleep(2)


for i in range(1, 10000):

    for j in range(1, random.randint(1, 5)):
        for i in arr:
            os.system('cls')
            print(i + " Loading" + dotdot +
                  (3 - len(dotdot)) * " " + " " + bar + (int(20 - percentage/5) * " ") + "] " + str(percentage) + "%" + " " + str(round(MB, 2)) + "mb")
            if len(dotdot) < 3:
                dotdot += "."
            else:
                dotdot = ""
                MB += 13.944 * random.uniform(0, 1)
            time.sleep(0.2)
    bar += "■"
    percentage += 5

    if percentage == 100:
        print("= India Scam Center Control Software 10.2.13 = ERROR: Install unsuccessful please try again. =")
        break

os.system('pause')
